version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1416sdps0fhqb"
s3_prefix = "cloud-resume"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"erichssamdeploycloudresumebucket\""
image_repositories = []
